#+BRAIN_CHILDREN: flesh

#+BRAIN_PARENTS: index

Jesus as archetype.

[[https://mullikine.github.io/posts/gospel-of-thomas/][An exergesis of the 'Gospel of Thomas' // Bodacious Blog]]

---

[[https://www.biblegateway.com/passage/?search=Colossians%202&version=KJV][Colossians 2]]

#+BEGIN_SRC text -n :async :results verbatim code
  8 Beware lest anyone [e]cheat you through
  philosophy and empty deceit, according to the
  tradition of men, according to the basic
  principles of the world, and not according to
  Christ. 9 For in Him dwells all the fullness
  of the Godhead [f]bodily; 10 and you are
  complete in Him, who is the head of all
  [g]principality and power.
#+END_SRC

* loves the Father
  :PROPERTIES:
  :ID:       b31653f7-8d34-4c8c-9a2a-4bf30bd3d66a
  :END:

+ [[https://biblehub.com/bsb/john/14.htm][John 14:30]] :: 30 I will not speak with you much longer, for the prince of this world is coming, and he has no claim on Me. 31 But I do exactly what the Father has commanded Me, so that the world may know that I love the Father.

* blameless
  :PROPERTIES:
  :ID:       3f41096d-0779-473d-86cf-5537d250f809
  :END:

+ [[https://biblehub.com/bsb/john/14.htm][John 14:30]] :: 30 I will not speak with you much longer, for the prince of this world is coming, and he has no claim on Me. 31 But I do exactly what the Father has commanded Me, so that the world may know that I love the Father.

Jesus was blameless.

I am not blameless, that is for certain.
I know that I have been tempted, and I have failed at times.

* divider or not?
  :PROPERTIES:
  :ID:       49ca374f-be75-488b-98e7-085a06bc8ab3
  :END:

The Parable of the Rich Fool

13 And one of the company said unto him,
Master, speak to my brother, that he divide
the inheritance with me. 14 And he said unto
him, Man, who made me a judge or a divider
over you? 15 And he said unto them, Take heed,
and beware of covetousness: for a man's life
consisteth not in the abundance of the things
which he possesseth. 16 And he spake a parable
unto them, saying, The ground of a certain
rich man brought forth plentifully: 17 And he
thought within himself, saying, What shall I
do, because I have no room where to bestow my
fruits? 18 And he said, This will I do: I will
pull down my barns, and build greater; and
there will I bestow all my fruits and my
goods. 19 And I will say to my soul, Soul, thou
hast much goods laid up for many years; take
thine ease, eat, drink, and be merry. 20 But
God said unto him, Thou fool, this night thy
soul shall be required of thee: then whose
shall those things be, which thou hast
provided? 21 So is he that layeth up treasure
for himself, and is not rich toward God.

---

Not Peace, But Division

(Matthew 10 :34 -36 )

49 I am come to send fire on the earth; and
what will I, if it be already kindled? 50 But I
have a baptism to be baptized with; and how am
I straitened till it be accomplished!
51 Suppose ye that I am come to give peace on
earth? I tell you, Nay; but rather division:
52 For from henceforth there shall be five in
one house divided, three against two, and two
against three. 53 The father shall be divided
against the son, and the son against the
father; the mother against the daughter, and
the daughter against the mother; the mother in
law against her daughter in law, and the
daughter in law against her mother in law.