#+BRAIN_PARENTS: index
:RESOURCES:
- [[https://en.wikipedia.org/wiki/Discernment]]
:END:


Discernment is the ability to obtain sharp
perceptions or to judge well (or the activity
of so doing).

In the case of judgement, discernment can be
psychological, moral or aesthetic in nature.

Discernment has also been defined in the
contexts; scientific (that is discerning what
is true about the real world), normative
(discerning value including what ought to be)
and formal (deductive reasoning).

The process of discernment within judgment,
involves going past the mere perception of
something and making nuanced judgments about
its properties or qualities.

Discernment in the Christian religion is
considered as a virtue, a discerning
individual is considered to possess wisdom,
and be of good judgement; especially so with
regard to subject matter often overlooked by
others.

In Christianity, the word may have several
meanings.

Discernment can describe the process of
determining God's desire in a situation or for
one's life or identifying the true nature of a
thing, such as discerning whether a thing is
good, evil, or may even transcend the limiting
notion of duality.

* hypocrisy
  :PROPERTIES:
  :ID:       1e133fb2-7f1d-4977-a510-cd105d3b12f5
  :END:

https://biblehub.com/niv/luke/12.htm

- Be on guard against the yeast of the pharisees, which is hypocrisy.
  - For example, 

* interpret the times
  :PROPERTIES:
  :ID:       0dfea336-e667-44aa-acd2-dbb0fc1a6810
  :END:

https://biblehub.com/niv/luke/12.htm

- We just endeavour to be reconciled unto one another.