#+BRAIN_FRIENDS: life

#+BRAIN_PARENTS: index

- https://lifehopeandtruth.com/life/life-after-death/immortal-soul/

* deep belief joins your spirit to Jesus
  :PROPERTIES:
  :ID:       9844048c-a348-43da-9317-04e81f2385b1
  :END:

https://biblehub.com/kjv/john/6.htm

47Verily, verily, I say unto you, He that
believeth on me hath everlasting life. 48I am
that bread of life. 49Your fathers did eat
manna in the wilderness, and are dead. 50This
is the bread which cometh down from heaven,
that a man may eat thereof, and not die. 51I
am the living bread which came down from
heaven: if any man eat of this bread, he shall
live for ever: and the bread that I will give
is my flesh, which I will give for the life of
the world.

52The Jews therefore strove among themselves,
saying, How can this man give us his flesh to
eat? 53Then Jesus said unto them, Verily,
verily, I say unto you, Except ye eat the
flesh of the Son of man, and drink his blood,
ye have no life in you. 54Whoso eateth my
flesh, and drinketh my blood, hath eternal
life; and I will raise him up at the last day.
55For my flesh is meat indeed, and my blood is
drink indeed. 56He that eateth my flesh, and
drinketh my blood, dwelleth in me, and I in
him. 57As the living Father hath sent me, and
I live by the Father: so he that eateth me,
even he shall live by me. 58This is that bread
which came down from heaven: not as your
fathers did eat manna, and are dead: he that
eateth of this bread shall live for ever.

* rid yourself of evil and deception
  :PROPERTIES:
  :ID:       20cf710b-f31f-4aa1-af97-3404b0b20418
  :END:

+ [[https://www.biblegateway.com/passage/?search=1%20Peter+2&version=KJV][1 Peter 2:1-2]] :: 2 Wherefore laying aside all malice, and all guile, and hypocrisies, and envies, and all evil speakings, 2 As newborn babes, desire the sincere milk of the word, that ye may grow thereby:

#+BEGIN_SRC text -n :async :results verbatim code
  guile
      Sly or cunning intelligence.
#+END_SRC
