#+BRAIN_PARENTS: index

* worship in spirit and truth
  :PROPERTIES:
  :ID:       43d6c393-0f03-4190-aea6-ac20425edad7
  :END:

[[https://www.youtube.com/watch?v=T33PNLOFtYo][What It Means To Worship In Spirit And Truth | Derek Prince - YouTube]]

---

For example, y:complementarianism vs y:egalitarianism.

I feel like the more Christians focus on the letter and less on the spirit, the more deceived they become. We live in a time where we need to be able to worship God in spirit and truth, not the letter.

2 Corinthians 3:6 He has made us competent as ministers of a new covenant—not of the letter but of the Spirit; for the letter kills, but the Spirit gives life. http://www.earlychristianwritings.com/thomas/gospelthomas114.html

The last saying in Gospel of Thomas. (114) Simon Peter said to him, "Let Mary leave us, for women are not worthy of life." Jesus said, "I myself shall lead her in order to make her male, so that she too may become a living spirit resembling you males. For every woman who will make herself male will
enter the kingdom of heaven."

